### ISSUE TITLE
The emptyLines options doesn't count correctly

### ISSUE THREAD

**Issue by andreashuetter** [aMarCruz/jspreproc#10]
{emptyLines: -1} does not preserve the correct number of lines.

For example, this input

```
1
/* TEST1 */
/* 

 TEST2

 */
2
 /* TEST3 */
3
```

is giving me

```
1


2

3
```

while it should be

```
1






2

3
```

**Comment by aMarCruz** [comment]
@andreashuetter this is by design, lines inside multiline comments are removed but you're right, these should be preserved to support sourcemaps. right? v0.3.0 will be have this behavior.
Thanks for your feedback.

ADD: It will be a new option and the lines occupied by conditional comments can also be preserved.

**Comment by andreashuetter** [comment]
@aMarCruz:
Thanks a lot, that would be really nice!

Your jspreproc package is great. Yet I have an idea for another improvement: I think it would be very helpful if there was a way to specify which characters should be used for comments. As it currently is, you can process not only JavaScript files but also Java files and C/C++ files because those languages are all using the same characters for comments: // for single line comments, /\* to start a multiline comment and */ to end a multiline comment.
But x86/x64 Assembly language for instance is using a semicolon (;) for single line comments (multiline comments are used the same way as in the other mentioned languages).
So if you'd just create the opportunity to specify an option for linecommentStart, blockcommentStart and blockcommentEnd, one could easily use your package also for Assembly Language files (and for many other languages as well).

Do you think this is doable?

**Comment by aMarCruz** [comment]
@andreashuetter sure it is possible. My current interest is about Javascript. I wrote this tool for use by some modules of [riotjs](http://riotjs.com/) (see `src` in [riot-compiler](https://github.com/riot/compiler) and `lib` in [riot-tmpl](https://github.com/riot/tmpl)). However, I think that it is not difficult to include this feature. I will put it on my TODO for v0.3.
Thanks!
