### ISSUE TITLE
Usage question 

### ISSUE THREAD

**Issue by linuxenko** [aMarCruz/jspreproc#11]
Hi 🎉 

Can you please provide an example of using `preproc` in tandem with build tools such as `webpack` or something like this ?

**Comment by aMarCruz** [comment]
@linuxenko sorry, I'm not a webpack user and not actively maintaining this repo.
However I made some plugins for [jscc](https://github.com/aMarCruz/jscc), which has most features of jspreproc (i.e. conditional inclusion and variable substitution).

Current plugins includes:

- [Rollup](https://www.npmjs.com/package/rollup-plugin-jscc)
- [Brunch](https://www.npmjs.com/package/jscc-brunch)
- [Gulp](https://www.npmjs.com/package/gulp-jscc)
- [Browserify](https://www.npmjs.com/package/jsccify) by @gucong3000

Maybe the code of this plugins help you.

**Comment by linuxenko** [comment]
So many plugins for different build systems, wow 🦄 

Thank you
